steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
- id: 'Docker Build'
  name: gcr.io/cloud-builders/docker
  args: [
    'build', 
    '-t', 
    'us-central1-docker.pkg.dev/$PROJECT_ID/omnicore-infra/management-api:$REVISION_ID',
     '-t',
     'us-central1-docker.pkg.dev/$PROJECT_ID/omnicore-infra/management-api:latest',
     '.'
   ]

- id: 'Push to Google ACR'
  name: gcr.io/cloud-builders/docker
  args: [
    'push', 
    'us-central1-docker.pkg.dev/$PROJECT_ID/omnicore-infra/management-api:$REVISION_ID'
  ]
  ###########
# Push the image to Google Container Registry with the latest tag
images: [
    'us-central1-docker.pkg.dev/$PROJECT_ID/omnicore-infra/management-api:$REVISION_ID'
  ]