steps:
#steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
- id: 'Docker Build'
  name: gcr.io/cloud-builders/docker
  args: [
    'build', 
    '-t', 
    'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_SERVICE_NAME}:$SHORT_SHA',
     '-t',
     'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_SERVICE_NAME}:latest',
     '.'
   ]
- id: 'Push to Google ACR'
  name: gcr.io/cloud-builders/docker
  args: [
    'push', 
    'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_SERVICE_NAME}:$SHORT_SHA'
  ]
images: [
    'us-central1-docker.pkg.dev/$PROJECT_ID/omnicore-infra/management-api:$REVISION_ID'
  ]
 
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - management-api-test
    - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_SERVICE_NAME}:$SHORT_SHA
    - --port=8080
    - --region=${_REGION}
    - --memory=512Mi
    - --platform=managed
    - --allow-unauthenticated
    - --min-instances=0
    - --max-instances=5
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_SERVICE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_SERVICE_NAME}:latest'
timeout: 1800s
